[mongodb]
host = 127.0.0.1
port = 27017
db_name = your db_name
username =
password =
auth_mechanism = SCRAM-SHA-256
connect_timeout_ms = 10000
server_selection_timeout_ms = 10000
socket_timeout_ms = 30000
max_pool_size = 100
min_pool_size = 0
retry_reads = true
retry_writes = true
connect_eagerly = false
